In [1]:
import pandas as pd
train_df = pd.read_csv("hindi_train.csv")
train_data = train_df[:8000]
test_data = train_df[8000:10000]
# print(train_data['Article'].iloc[0])

In [2]:
from IPython.display import display

print("Training Dataset (Number of samples: {})".format(train_data.shape[0]))
train_data.drop(columns=['Id'], inplace=True)
display(train_data.head())

print("\nTest Dataset (Number of samples: {})".format(test_data.shape[0]))
test_data.drop(columns=['Id'], inplace=True)
display(test_data.head())

Training Dataset (Number of samples: 8000)

C:\Users\HP\AppData\Local\Temp\ipykernel_15244\851011858.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop(columns=['Id'], inplace=True)

,Heading,Summary,Article
0,"गला दबाकर हत्या की; बॉडी बोरे में भरी, लोकल मा...",Kerala Minor Girl Rape Case - केरल के एर्नाकुल...,केरल के एर्नाकुलम जिले में 5 साल की बच्ची से र...
1,तेलंगाना में 18 की जान गई; जम्मू-कश्मीर में बा...,इस साल मानसून सीजन में कई राज्यों में भारी तबा...,मानसून सीजन में हुई भारी बारिश ने कई राज्यों म...
2,"राजस्थान सरकार बनाएगी कर्ज राहत आयोग, कोर्ट के...",चुनावी साल में राजस्थान सरकार किसानों को लुभान...,चुनावी साल में राजस्थान सरकार किसानों को लुभान...
3,"3 से 7 अगस्त तक कर सकेंगे अप्लाय, प्राइस बैंड ...",Non-banking lender SBFC Finance's initial publ...,नॉन बैंकिग फाइनेंस कंपनी 'SBFC फाइनेंस लिमिटेड...
4,"डाइनिंग टेबल पर कुकर-कड़ाही न सजाएं, चीन के खा...",स्वाद खाने की बुनियाद है। लेकिन अगर खाना सुंदर...,स्वाद खाने की बुनियाद है। लेकिन अगर खाना सुंदर...

Test Dataset (Number of samples: 2000)

C:\Users\HP\AppData\Local\Temp\ipykernel_15244\851011858.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.drop(columns=['Id'], inplace=True)

,Heading,Summary,Article
8000,सारा अली खान ने शेयर किया हिमाचल ट्रिप का मजेद...,Bollywood Actress Sara Ali Khan Himachal Prade...,बॉलीवुड एक्ट्रेस सारा अली खान हाल ही में अपनी ...
8001,हर महीने 500 मिलते थे; आज करोड़ो रुपए टैक्स दे...,Bollywood Actor Kapil Sharma On His First Sala...,कपिल शर्मा देश के उन चुनिंदा सेलिब्रिटीज में स...
8002,"कहा- मिलेट्स की कामयाबी भारत की जिम्मेदारी, यह...",Prime Minister Narendra Modi Global Millets Co...,प्रधानमंत्री नरेंद्र मोदी ने नई दिल्ली में होन...
8003,"हर प्रश्न के साथ देखिए उसका उत्तर, क्लियर करें...",RSMSSB REET Answer Sheet; Rajasthan Examinatio...,राजस्थान के लाखों युवाओं का इंतजार खत्म हो गया...
8004,"भारत में नीयत पाक, सुषमा ने ट्रेजरी को दे दी थ...",Former Prime Minister Imran Khan Income Detail...,पाकिस्तान में बवाल मचा हुआ है…बवाल भी पूर्व प्...

In [3]:
import re
import emoji
from num_to_words import num_to_word

def preprocess_text(text):
    """
    Preprocess the given text.

    Parameters:
    - text (str): The text to be preprocessed

    Returns:
    - str: Preprocessed text.
    """
    # Convert emojis to textual representations and remove emoji placeholders
    text = re.sub(r':[a-zA-Z_]+:', ' ', emoji.demojize(str(text)))
    # Remove newline, carriage return, and tab characters, underscores, hyphens, tildes, plus signs, special characters,
    text = re.sub(r'[\n\r\t_\-~\+\s]{2,}|[<>()&©@#ø\[\]\'\",;:‘’]', ' ', str(text).replace('\u200d', '').lower())
    text = re.sub("([a-zA-Z])",' ',str(text)).lower() # (*Note : currently removing english or we can convert it to hindi using API*) --- For English Removal
    text = re.sub("(\s+)",' ',str(text)).lower() # remove multiple spaces.
    # Convert numeric values to their word representation
    text = re.sub(r'\b(\d+)\b', lambda x: num_to_word(int(x.group(0)), lang='hi'), text)
    text = re.sub(r'[\n\r\t_\-~\+\s]{2,}|[<>()&©@#ø\[\]\'\",;:‘’]', ' ', str(text).replace('\u200d', '').lower())
    return text.strip()

# Example usage:
text_to_preprocess = "केरल के एर्नाकुलम जिले में 5 साल की बच्ची से रेप के बाद गला दबाकर हत्या कर दी गई। आरोपी ने बच्ची का शव बोरे में डालकर डंपिंग ग्राउंड में फेंक दिया था। पुलिस ने आरोपी शख्स को गिरफ्तार कर लिया है। घटना शुक्रवार शाम की है। पुलिस ने शनिवार को मीडिया को इसकी जानकारी दी।"
preprocessed_text = preprocess_text(text_to_preprocess)
print(preprocessed_text)

केरल के एर्नाकुलम जिले में पाँच साल की बच्ची से रेप के बाद गला दबाकर हत्या कर दी गई। आरोपी ने बच्ची का शव बोरे में डालकर डंपिंग ग्राउंड में फेंक दिया था। पुलिस ने आरोपी शख्स को गिरफ्तार कर लिया है। घटना शुक्रवार शाम की है। पुलिस ने शनिवार को मीडिया को इसकी जानकारी दी।

In [4]:
from IPython.display import display
from tqdm import tqdm  # Import tqdm

# Preprocess all columns of the training dataset
print("Training Dataset (Number of samples: {})".format(train_data.shape[0]))
for col in train_data.columns:
    tqdm.pandas(desc=f"Preprocessing {col}")  # Add tqdm progress bar for each column
    train_data[col] = train_data[col].progress_apply(preprocess_text)
display(train_data.head())

# Preprocess all columns of the test dataset
print("\nTest Dataset (Number of samples: {})".format(test_data.shape[0]))
for col in test_data.columns:
    tqdm.pandas(desc=f"Preprocessing {col}")  # Add tqdm progress bar for each column
    test_data[col] = test_data[col].progress_apply(preprocess_text)
display(test_data.head())

Training Dataset (Number of samples: 8000)

Preprocessing Heading: 100%|██████████| 8000/8000 [00:00<00:00, 10085.87it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = train_data[col].progress_apply(preprocess_text)
Preprocessing Summary: 100%|██████████| 8000/8000 [00:02<00:00, 3674.28it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = train_data[col].progress_apply(preprocess_text)
Preprocessing Article: 100%|██████████| 8000/8000 [00:29<00:00, 273.61it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[col] = train_data[col].progress_apply(preprocess_text)

,Heading,Summary,Article
0,गला दबाकर हत्या की बॉडी बोरे में भरी लोकल मार्...,केरल के एर्नाकुलम जिले में पाँच साल की बच्ची स...,केरल के एर्नाकुलम जिले में पाँच साल की बच्ची स...
1,तेलंगाना में अट्ठारह की जान गई जम्मू-कश्मीर मे...,इस साल मानसून सीजन में कई राज्यों में भारी तबा...,मानसून सीजन में हुई भारी बारिश ने कई राज्यों म...
2,राजस्थान सरकार बनाएगी कर्ज राहत आयोग कोर्ट के ...,चुनावी साल में राजस्थान सरकार किसानों को लुभान...,चुनावी साल में राजस्थान सरकार किसानों को लुभान...
3,तीन से सात अगस्त तक कर सकेंगे अप्लाय प्राइस बै...,| नॉन बैंकिग फाइनेंस कंपनी फाइनेंस लिमिटेड का ...,नॉन बैंकिग फाइनेंस कंपनी फाइनेंस लिमिटेड का पब...
4,डाइनिंग टेबल पर कुकर-कड़ाही न सजाएं चीन के खान...,स्वाद खाने की बुनियाद है। लेकिन अगर खाना सुंदर...,स्वाद खाने की बुनियाद है। लेकिन अगर खाना सुंदर...

Test Dataset (Number of samples: 2000)

Preprocessing Heading: 100%|██████████| 2000/2000 [00:00<00:00, 9186.20it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[col] = test_data[col].progress_apply(preprocess_text)
Preprocessing Summary: 100%|██████████| 2000/2000 [00:00<00:00, 3615.26it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[col] = test_data[col].progress_apply(preprocess_text)
Preprocessing Article: 100%|██████████| 2000/2000 [00:07<00:00, 269.20it/s]
C:\Users\HP\AppData\Local\Temp\ipykernel_15244\4155927934.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[col] = test_data[col].progress_apply(preprocess_text)

,Heading,Summary,Article
8000,सारा अली खान ने शेयर किया हिमाचल ट्रिप का मजेद...,बॉलीवुड एक्ट्रेस सारा अली खान हाल ही में अपनी ...,बॉलीवुड एक्ट्रेस सारा अली खान हाल ही में अपनी ...
8001,हर महीने पाँच सौ मिलते थे आज करोड़ो रुपए टैक्स...,चौदह कपिल शर्मा देश के उन चुनिंदा सेलिब्रिटिज ...,कपिल शर्मा देश के उन चुनिंदा सेलिब्रिटीज में स...
8002,कहा मिलेट्स की कामयाबी भारत की जिम्मेदारी यह द...,प्रधानमंत्री नरेंद्र मोदी आज ग्लोबल मिलेट्स मो...,प्रधानमंत्री नरेंद्र मोदी ने नई दिल्ली में होन...
8003,हर प्रश्न के साथ देखिए उसका उत्तर क्लियर करें ...,. राजस्थान के लाखों युवाओं के इंतजार खत्म हो ग...,राजस्थान के लाखों युवाओं का इंतजार खत्म हो गया...
8004,भारत में नीयत पाक सुषमा ने ट्रेजरी को दे दी थी...,हर देश के राष्ट्रपति-प्रधानमंत्री से लेकर सरका...,पाकिस्तान में बवाल मचा हुआ है…बवाल भी पूर्व प्...

In [6]:
#Reference: https://www.kaggle.com/code/mahitnandanad/mandate-2
import pandas as pd
import math
from nltk.tokenize import SpaceTokenizer
stopwords=['अर्थात', 'कुछ', 'तेरी', 'साबुत', 'अपनि', 'हूं', 'काफि', 'यिह', 'जा', 'दे', 'देकर', 'रह', 'कह', 'कहा', 'बात' , 'जिन्हों', 'किर', 'कोई', 'हे', 'कोन', 'रहा', 'सब', 'सो', 'तक', 'इंहें', 'इसकि', 'अपनी', 'दबारा', 'सभि', 'होते', 'भीतर', 'निचे', 'घर', 'उन्हें', 'उन्ह', 'मेरे', 'था', 'व', 'इसमें', 'उसी', 'बिलकुल', 'होति', 'गया', 'सकता', 'अपना', 'लिये', 'उसका', 'पर', 'दवारा', 'गए', 'है', 'कितना', 'भि', 'लिए', 'वुह ', 'ना', 'किसि', 'परन्तु', 'किन्हें', 'बहुत', 'भी', 'तुम्हारे', 'निहायत', 'उन्हीं', 'वहिं', 'हैं', 'उन्हों', 'इतयादि' ,'यहाँ', 'तब', 'पूरा', 'क्योंकि', 'कौनसा', 'आप', 'हुअ', 'ऐसे', 'एस', 'कारण', 'अप', 'पहले', 'तुम', 'जेसा', 'तिस', 'लेकिन', 'कहते', 'मगर', 'करता', 'संग', 'सभी', 'जीधर', 'किंहों', 'हि', 'द्वारा', 'हुआ', 'तू', 'जिंहें', 'उसने', 'पास', 'वहां', 'वह', 'किंहें', 'इंहों', 'मुझ', 'कुल', 'तिंहों', 'का', 'मेरी', 'तेरे', 'उनके', 'क्या', 'जहाँ', 'काफ़ी', 'वर्ग', 'वरग', 'बही', 'ये', 'जिस', 'इसि', 'हुई', 'साम्हने', 'नहिं', 'जैसे', 'वहीं', 'दिया', 'अभी', 'यहि', 'वग़ैरह', 'उनकि', 'न', 'बनि', 'हें', 'यिह ', 'उन', 'को', 'तिन्हों', 'उन्होंने', 'तुझे', 'उसे', 'होने', 'इन्हीं', 'थे', 'उंहिं', 'अपने', 'में', 'फिर', 'यही', 'नीचे', 'होती', 'तिसे', 'हम', 'यदि', 'सारा', 'कर', 'सकते', 'कोइ', 'और', 'जिंहों', 'तिंहें', 'दूसरे', 'जब', 'रहे', 'अत', 'मानो', 'जिन', 'बाद', 'उनका', 'किया', 'या', 'उनकी', 'कौन', 'ऐसा', 'सबसे', 'अनुसार', 'दुसरे', 'इन', 'अदि', 'जिसे', 'उसकी', 'इत्यादि', 'करना', 'यहां', 'हुए', 'तेरा', 'आदि', 'पर  ', 'वाले', 'कहता', 'किन्हों', 'किसे', 'जिन्हें', 'मे', 'होता', 'करने', 'साभ', 'अभि', 'उसको', 'कई', 'बनी', 'के', 'इन्हें', 'वहाँ', 'कोनसा', 'कइ', 'इनका', 'थि', 'बाला', 'ऱ्वासा', 'हो', 'उंहें', 'दुसरा', 'वे', 'भितर', 'जेसे', 'एवं', 'अंदर', 'दो', 'साथ', 'करें', 'जिधर', 'तरह', 'उसि', 'इस', 'एसे', 'तिन', 'नहीं', 'से', 'न', 'उनको', 'किस', 'किसी', 'इसी', 'मैं', 'यह', 'हुइ', 'ले', 'कि', 'की', 'इसलिये', 'रवासा', 'ने', 'जैसा', 'वह ', 'तिन्हें', 'वुह', 'उस', 'उंहों', 'वगेरह', 'उसके', 'मुझे', 'करते', 'जितना', 'जहां', 'इन्हों', 'इसके', 'होना', 'इसका', 'इंहिं', 'एक', 'जो', 'पे', 'ही', 'तो', 'थी', 'रखें', 'इसे', 'इन ', 'के', 'बहि', 'पुरा', 'ओर', 'इसकी']
stopwords.extend(['में','के','है','से'])

In [7]:
def remove_redundant_sentences(sentences):
    cleaned=[]
    for s in sentences:
        if s in cleaned or s.strip()=='':
            continue
        else:
            cleaned.append(s)
    return cleaned

def get_clean_sentences(doc):
    doc=doc.replace('।','.')
    doc=doc.replace('\xa0','')
    doc=doc.replace('\n','')
    doc=doc.replace('\r','')
    sentences=doc.split('.')
    sentences=remove_redundant_sentences(sentences)
    return sentences

In [11]:
def average_sentence_value(sentenceValues):
    sum_values=0
    for sent_id in sentenceValues:
        sum_values+=sentenceValues[sent_id]
    sent_count=len(sentenceValues)
    return sum_values/sent_count

def generate_summary(avg_score,sentences,sentenceValue,identifier):
    sentence_count=0
    summary=''
    for sentence in sentences:
        if sentence[:identifier] in sentenceValue and sentenceValue[sentence[:identifier]]>=avg_score:
            summary+=sentence.strip()+"| "
            sentence_count+=1
    return summary,sentence_count

def calc_term_frequency_sentence_wise(sentences):
    freq_matrix={}
    for sentence in sentences:
        words=SpaceTokenizer().tokenize(sentence)
        sent_freq_table={}
        for word in words:
            if word in stopwords:
                continue
            if word in sent_freq_table:
                sent_freq_table[word]+=1
            else:
                sent_freq_table[word]=1
        freq_matrix[sentence[:15]]=sent_freq_table
    return freq_matrix
        
def calc_tf_matrix(freq_matrix):
    for sentence,sent_freq_table in freq_matrix.items():
        tf_sent={}
        sent_len=len(sent_freq_table)
        for word in sent_freq_table:
            sent_freq_table[word]/=sent_len
    return freq_matrix

def calc_sentence_frequency(freq_matrix):
    sent_freq={}
    for sentence,freq_matrix_sent in freq_matrix.items():
        for word,count in freq_matrix_sent.items():
            if word in sent_freq:
                sent_freq[word]+=1
            else:
                sent_freq[word]=1
    return sent_freq

def calc_idf_score(total_sentences,sent_freq,freq_matrix):
    idf={}
    for sentence,freq_matrix_sent in freq_matrix.items():
        idf_sent={}
        for word in freq_matrix_sent:
            idf_sent[word]=math.log10(total_sentences / float(sent_freq[word]))
        idf[sentence]=idf_sent
    return idf
    
def calc_tf_idf_score(tf,idf):
    tf_idf={}
    for (sentence1,tf_sent),(sentence2,idf_sent) in zip(tf.items(),idf.items()):
        tf_idf_sent={}
        for (word1,tf_score),(word2,idf_score) in zip(tf_sent.items(),idf_sent.items()):
            tf_idf_sent[word1]=tf_score*idf_score
        tf_idf[sentence1]=tf_idf_sent
    return tf_idf

def calc_tf_idf_score_sentence_wise(tf_idf_matrix):
    tf_idf={}
    for sentence,tf_idf_sent in tf_idf_matrix.items():
        tf_idf_sentence=0
        for word,tf_idf_score in tf_idf_sent.items():
            tf_idf_sentence+=tf_idf_score
        tf_idf[sentence]=tf_idf_sentence
    return tf_idf

In [12]:
def get_tf_idf(sentences):
    sent_freq_matrix=calc_term_frequency_sentence_wise(sentences)
    freq_matrix=calc_tf_matrix(sent_freq_matrix)
    total_sentences=len(sentences)
    sent_freq=calc_sentence_frequency(freq_matrix)
    idf=calc_idf_score(total_sentences,sent_freq,freq_matrix)
    tf_idf_matrix=calc_tf_idf_score(freq_matrix,idf)
    tf_idf=calc_tf_idf_score_sentence_wise(tf_idf_matrix)
    return tf_idf

def summarise_tf_idf_sentence_weighting(sentences):
    tf_idf=get_tf_idf(sentences)
    sentences=remove_redundant_sentences(sentences)
    avg_tf_idf_score=average_sentence_value(tf_idf)
    tf_idf_summary,sent_count=generate_summary(avg_tf_idf_score,sentences,tf_idf,15)
    return tf_idf_summary

In [13]:
SystemSummary_tf = []
for index, row in tqdm(test_data.iterrows(), total=len(test_data)):
    summary = summarise_tf_idf_sentence_weighting(get_clean_sentences(row['Article']))
    SystemSummary_tf.append(summary)

100%|██████████| 2000/2000 [00:04<00:00, 476.01it/s]

In [14]:
Summaries_tf = pd.DataFrame(list(zip(test_data['Summary'], SystemSummary_tf)), columns =['GoldSummary', 'tfSummary'])
Summaries_tf

,GoldSummary,tfSummary
0,बॉलीवुड एक्ट्रेस सारा अली खान हाल ही में अपनी ...,बॉलीवुड एक्ट्रेस सारा अली खान हाल ही में अपनी ...
1,चौदह कपिल शर्मा देश के उन चुनिंदा सेलिब्रिटिज ...,इसके बाद पॉकेट मनी की जुगाड़ में चौदह साल की उ...
2,प्रधानमंत्री नरेंद्र मोदी आज ग्लोबल मिलेट्स मो...,यह कॉन्फ्रेंस दिल्ली के इंडियन एग्रीकल्चर रिसर...
3,. राजस्थान के लाखों युवाओं के इंतजार खत्म हो ग...,राजस्थान के लाखों युवाओं का इंतजार खत्म हो गया...
4,हर देश के राष्ट्रपति-प्रधानमंत्री से लेकर सरका...,पाकिस्तान में बवाल मचा हुआ है…बवाल भी पूर्व प्...
...,...,...
1995,प्रधानमंत्री नरेंद्र मोदी ने खेती किसानी से जु...,नई दिल्ली| मैं अपने किसान भाइयों और बहनों को आ...
1996,भारतीय किसान यूनियन के प्रवक्ता राकेश टिकैत ने...,भारतीय किसान यूनियन के प्रवक्ता राकेश टिकैत ने...
1997,अवनीश अवस्थी और एचसी अवस्थी ने पीड़ित परिवार स...,हाथरस अपर मुख्य सचिव गृह अवनीश अवस्थी और पुलिस...
1998,उत्तर प्रदेश में एक बार फिर प्रशासनिक फेरबदल क...,उत्तर प्रदेश में एक बार फिर प्रशासनिक फेरबदल क...
1999,पंजाब के पूर्व मुख्यमंत्री कैप्टन अमरिंदर सिंह...,बताया जाता है कि पाँच जनपथ पर नेशनल सिक्योरिटी...

In [15]:
from rouge import Rouge
rouge = Rouge()
score = rouge.get_scores(Summaries_tf['tfSummary'], Summaries_tf['GoldSummary'], avg=True)
T5Rouge = pd.DataFrame(score).set_index([['recall','precision','f-measure']])
T5Rouge

            rouge-1   rouge-2   rouge-l
recall     0.738707  0.495820  0.624351
precision  0.117311  0.060360  0.099951
f-measure  0.190881  0.099406  0.161956

In [16]:
from bert_score import score

tf_summaries = Summaries_tf['tfSummary'].tolist()
gold_summaries = Summaries_tf['GoldSummary'].tolist()

P, R, F1 = score(cands=tf_summaries, refs=gold_summaries, lang='hi', model_type='bert-base-multilingual-cased')

print("BERTScore Precision:", P.mean().item())
print("BERTScore Recall:", R.mean().item())
print("BERTScore F1:", F1.mean().item())

BERTScore Precision: 0.6284134387969971
BERTScore Recall: 0.776731550693512
BERTScore F1: 0.6939938068389893